name: (Rahat Ullah Devops Engineer)

on:
  push:
    branches: ["master"]
  pull_request:
   branches: ["master"]


jobs:
  myjob_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU test
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rahatullah123  
          password: pakistan123PPPP
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rahatullah123/bushra:v7
  myjob_pull:
    
    runs-on: [self-hosted, Linux ,X64 ,staging]
    needs: myjob_build
    steps:
    
      -
        name: Set up QEMU test
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rahatullah123  
          password: pakistan123PPPP
      -
        name: Build and push
        run: docker run -p 80:8080 -e APP_COLOR=purple rahatullah123/bushra:v7
      
